-- ------------------------------------------------------------
-- R__test_announcement.sql
-- テスト用 アナウンスマスタ データ
-- code_type:0027（AnnouncementScope）の全スコープ 1件ずつ
-- ------------------------------------------------------------

INSERT INTO m_announcement (
    title_ja, title_en, title_es,
    body_ja, body_en, body_es,
    severity, target_scope, start_at, end_at,
    create_user_id, create_program, created_at,
    update_user_id, update_program, updated_at
) VALUES
    ('全体メンテナンスのお知らせ',
     'System Maintenance Notice',
     'Aviso de mantenimiento del sistema',
     '2025年3月1日（土）2:00〜4:00にシステムメンテナンスを実施します。ご不便をおかけしますがご了承ください。',
     'System maintenance will be performed on March 1, 2025 from 2:00 to 4:00. We apologize for any inconvenience.',
     'Se realizará mantenimiento del sistema el 1 de marzo de 2025 de 2:00 a 4:00. Pedimos disculpas por las molestias.',
     'WARN', 'ALL',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('ホーム画面の新機能について',
     'New Feature on Home Screen',
     'Nueva función en la pantalla de inicio',
     'ホーム画面にお知らせバナーが追加されました。重要なお知らせをいち早くお届けします。',
     'An announcement banner has been added to the home screen to deliver important notices promptly.',
     'Se ha añadido un banner de anuncios a la pantalla de inicio para entregar avisos importantes.',
     'INFO', 'HOME',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('家事割り当て機能の障害について',
     'Housework Assignment Feature Issue',
     'Problema con la función de asignación de tareas',
     '現在、家事割り当て機能の一部で表示が遅くなる障害が発生しています。復旧まで今しばらくお待ちください。',
     'There is currently an issue causing slow display in part of the housework assignment feature. Please wait while we restore service.',
     'Actualmente hay un problema que causa lentitud en la función de asignación de tareas. Por favor espere mientras restauramos el servicio.',
     'ERROR', 'HW_ASSIGN',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('マイタスク画面の更新について',
     'My Tasks Screen Update',
     'Actualización de la pantalla Mis tareas',
     'マイタスク画面のUIが更新されました。より使いやすくなりましたのでぜひお試しください。',
     'The My Tasks screen UI has been updated. Please try out the improved usability.',
     'La interfaz de la pantalla Mis tareas ha sido actualizada. Pruebe la mejora de usabilidad.',
     'INFO', 'HW_TASK',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('家事設定の変更について',
     'Housework Settings Change Notice',
     'Aviso de cambio en configuración de tareas',
     '家事設定画面の項目が一部変更されました。設定内容をご確認ください。',
     'Some items on the Housework Settings screen have changed. Please review your settings.',
     'Algunos elementos de la pantalla de Configuración de tareas han cambiado. Por favor revise su configuración.',
     'WARN', 'HW_CONF',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('買い物リスト機能の改善について',
     'Shopping List Feature Improvement',
     'Mejora de la función de lista de compras',
     '買い物リスト画面のパフォーマンスが改善されました。より快適にお使いいただけます。',
     'The performance of the shopping list screen has been improved for a smoother experience.',
     'El rendimiento de la pantalla de lista de compras ha mejorado para una experiencia más fluida.',
     'INFO', 'SHOPPING',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('アカウント設定の緊急メンテナンス',
     'Emergency Maintenance for Account Settings',
     'Mantenimiento de emergencia para la configuración de cuenta',
     'アカウント設定画面に緊急メンテナンスを実施します。一時的にご利用いただけない場合があります。',
     'Emergency maintenance will be performed on the Account Settings screen. Access may be temporarily unavailable.',
     'Se realizará mantenimiento de emergencia en la pantalla de Configuración de cuenta. El acceso puede estar temporalmente no disponible.',
     'ERROR', 'CONF_ACCT',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('世帯設定に新項目が追加されました',
     'New Items Added to Household Settings',
     'Nuevos elementos añadidos a la configuración del hogar',
     '世帯設定にメンバー招待機能が追加されました。ぜひご活用ください。',
     'A member invitation feature has been added to Household Settings. Please make use of it.',
     'Se ha añadido una función de invitación de miembros a Configuración del hogar. Por favor úsela.',
     'INFO', 'CONF_HH',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('アプリ設定画面の注意事項',
     'Notes on App Settings Screen',
     'Notas sobre la pantalla de configuración de la app',
     'アプリ設定でテーマを変更した場合、一部の画面で反映に時間がかかることがあります。',
     'When changing the theme in App Settings, it may take some time for the change to reflect on some screens.',
     'Al cambiar el tema en Configuración de la app, puede llevar tiempo que el cambio se refleje en algunas pantallas.',
     'WARN', 'CONF_APP',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('通知機能の障害発生中',
     'Notification Feature Outage',
     'Interrupción de la función de notificaciones',
     '現在、通知機能に障害が発生しており、一部の通知が届かない状態です。復旧作業中です。',
     'The notification feature is currently experiencing an outage and some notifications may not be delivered. We are working to restore service.',
     'La función de notificaciones está experimentando una interrupción y algunas notificaciones pueden no entregarse. Estamos trabajando para restaurar el servicio.',
     'ERROR', 'NOTIFY',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('お問い合わせ対応時間の変更',
     'Change in Inquiry Response Hours',
     'Cambio en el horario de atención a consultas',
     'お問い合わせへの対応時間が平日9:00〜18:00に変更となりました。',
     'Inquiry response hours have changed to weekdays 9:00-18:00.',
     'El horario de atención a consultas ha cambiado a días hábiles de 9:00 a 18:00.',
     'INFO', 'INQUIRY',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6)),

    ('管理画面の権限ポリシー変更',
     'Admin Screen Permission Policy Change',
     'Cambio en la política de permisos de la pantalla de administración',
     '管理画面へのアクセス権限ポリシーが変更されました。権限設定をご確認ください。',
     'The access permission policy for the Admin screen has changed. Please review your permission settings.',
     'La política de permisos de acceso a la pantalla de administración ha cambiado. Por favor revise su configuración de permisos.',
     'WARN', 'ADMIN',
     '2025-01-01 00:00:00.000000', '2030-12-31 23:59:00.000000',
     1, 'SEED_DATA', NOW(6), 1, 'SEED_DATA', NOW(6));
